language: php
php:
    - 5.3

env:
  - SYMFONY_VERSION=v2.0.13
  - SYMFONY_VERSION=origin/master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit
